/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_mastermind;

import javax.swing.*;
import java.awt.*;

public class AccueilFenetre extends JFrame {

    public AccueilFenetre() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Ouvrir en plein écran
        setTitle("Accueil - Mastermind");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Contenu principal
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());

        // Titre
        JLabel lblTitre = new JLabel("Mastermind", SwingConstants.CENTER);
        lblTitre.setFont(new Font("Arial", Font.BOLD, 48)); // Double la taille du texte
        mainPanel.add(lblTitre, BorderLayout.NORTH);

        // Règles du jeu
        JTextPane txtRegles = new JTextPane();
        txtRegles.setContentType("text/html"); // Pour supporter du HTML
        txtRegles.setText("""
            <html>
                <div style='text-align: center; font-size: 20px;'>
                    <p><strong>Bienvenue dans le jeu du Mastermind !</strong></p>
                    <p>- Trouvez la combinaison secrète en un maximum de 12 essais.</p>
                    <p>- Chaque essai est constitué de 4 couleurs choisies parmi : 
                        <span style='color: red;'>Rouge</span>, 
                        <span style='color: blue;'>Bleu</span>, 
                        <span style='color: green;'>Vert</span>, 
                        <span style='color: yellow;'>Jaune</span>.
                    </p>
                    <p>- Les indices indiquent le nombre de pions <strong>bien placés</strong> et <strong>mal placés</strong>.</p>
                    <p>Bonne chance !</p>
                </div>
            </html>
        """);
        txtRegles.setEditable(false);
        mainPanel.add(new JScrollPane(txtRegles), BorderLayout.CENTER);

        // Bouton "Jouer"
        JButton btnJouer = new JButton("Jouer");
        btnJouer.setFont(new Font("Arial", Font.BOLD, 32)); // Double la taille du texte
        btnJouer.setPreferredSize(new Dimension(200, 100)); // Bouton plus grand
        btnJouer.addActionListener(e -> {
            new MasterMindInter().setVisible(true); // Lancer la fenêtre principale
            dispose(); // Fermer la fenêtre actuelle
        });
        mainPanel.add(btnJouer, BorderLayout.SOUTH);

        add(mainPanel);
    }

 

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Lancer l'application
        SwingUtilities.invokeLater(() -> {
            AccueilFenetre accueil = new AccueilFenetre();
            accueil.setVisible(true);
        });
    
    
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilFenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
