/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_mastermind;

import javax.swing.JTextField;

/**
 *
 * @author julia
 */

public class MasterMindInter extends javax.swing.JFrame {
private int ligneVisible = 0;
private void initGrille() {
    grillePanel.removeAll(); // Supprime les anciens composants si existants
    for (int i = 0; i < 12 * 4; i++) {
        JTextField champ = new JTextField();
        champ.setEditable(false); // Champs inactifs par défaut
        champ.setVisible(i < 4);  // Montre uniquement la première ligne
        grillePanel.add(champ);
        
    }
    grillePanel.revalidate();
    grillePanel.repaint();
        
}
private void afficherProchaineLigne() {
    ligneVisible++;
    for (int i = ligneVisible * 4; i < (ligneVisible + 1) * 4; i++) {
        if (i < grillePanel.getComponentCount()) {
            grillePanel.getComponent(i).setVisible(true);
        }
    }
    grillePanel.revalidate();
    grillePanel.repaint();
}
    /**
     * Creates new form MasterMindInter
     */
   public MasterMindInter() {
    initComponents();
    initGrille();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        grillePanel = new javax.swing.JPanel();
        validerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("<html> <center>Bienvenue dans Mastermind !<br>Devinez la combinaison en un maximum de 12 tours.</center> </html>");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        grillePanel.setBackground(new java.awt.Color(204, 204, 204));
        grillePanel.setLayout(new java.awt.GridLayout(12, 4));
        getContentPane().add(grillePanel, java.awt.BorderLayout.CENTER);

        validerButton.setText("Valider");
        getContentPane().add(validerButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMindInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grillePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
