/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_mastermind;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author julian
 */
public class MasterMindInter extends javax.swing.JFrame {
    private int ligneVisible = 0;
    private String[] combinaisonSecrete = {"Rouge", "Bleu", "Jaune", "Vert"}; // Combinaison secrète

    public MasterMindInter() {
        initComponents();
        initGrille();
    }

    private void initGrille() {
        grillePanel.removeAll(); // Supprime les anciens composants si existants
        String[] couleurs = {"Rouge", "Bleu", "Vert", "Jaune"}; // Couleurs disponibles

        for (int i = 0; i < 12 * 4; i++) {
            JComboBox<String> comboBox = new JComboBox<>(couleurs); // Crée une JComboBox avec les couleurs
            comboBox.setVisible(i < 4); // Montre uniquement la première ligne
            grillePanel.add(comboBox); // Ajoute la JComboBox au panneau
        }

        grillePanel.revalidate();
        grillePanel.repaint();
    }

    private void afficherProchaineLigne() {
        ligneVisible++;
        for (int i = ligneVisible * 4; i < (ligneVisible + 1) * 4; i++) {
            if (i < grillePanel.getComponentCount()) {
                grillePanel.getComponent(i).setVisible(true); // Rendre visible la prochaine ligne
            }
        }
        grillePanel.revalidate();
        grillePanel.repaint();
    }

    private String comparerCombinaisons(String[] proposition, String[] secret) {
        int bienPlaces = 0;
        int malPlaces = 0;
        boolean[] positionsMarquees = new boolean[secret.length];
        boolean[] positionsTestees = new boolean[proposition.length];

        // Étape 1 : Trouver les bien placés
        for (int i = 0; i < proposition.length; i++) {
            if (proposition[i].equals(secret[i])) {
                bienPlaces++;
                positionsMarquees[i] = true; // Marque la position dans la combinaison secrète
                positionsTestees[i] = true; // Marque la position dans la proposition
            }
        }

        // Étape 2 : Trouver les mal placés
        for (int i = 0; i < proposition.length; i++) {
            if (!positionsTestees[i]) {
                for (int j = 0; j < secret.length; j++) {
                    if (!positionsMarquees[j] && proposition[i].equals(secret[j])) {
                        malPlaces++;
                        positionsMarquees[j] = true; // Marque la position dans la combinaison secrète
                        break;
                    }
                }
            }
        }

        return "Bien placés : " + bienPlaces + " | Mal placés : " + malPlaces;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        grillePanel = new javax.swing.JPanel();
        Ligne1Colonne1 = new javax.swing.JComboBox<>();
        Ligne1Colonne2 = new javax.swing.JComboBox<>();
        Ligne1Colonne3 = new javax.swing.JComboBox<>();
        Ligne1Colonne4 = new javax.swing.JComboBox<>();
        Ligne2Colonne1 = new javax.swing.JComboBox<>();
        Ligne2Colonne2 = new javax.swing.JComboBox<>();
        Ligne2Colonne3 = new javax.swing.JComboBox<>();
        Ligne2Colonne4 = new javax.swing.JComboBox<>();
        Ligne3Colonne1 = new javax.swing.JComboBox<>();
        Ligne3Colonne2 = new javax.swing.JComboBox<>();
        Ligne3Colonne3 = new javax.swing.JComboBox<>();
        Ligne3Colonne4 = new javax.swing.JComboBox<>();
        Ligne4Colonne1 = new javax.swing.JComboBox<>();
        Ligne4Colonne2 = new javax.swing.JComboBox<>();
        Ligne4Colonne3 = new javax.swing.JComboBox<>();
        Ligne4Colonne4 = new javax.swing.JComboBox<>();
        Ligne5Colonne1 = new javax.swing.JComboBox<>();
        Ligne5Colonne2 = new javax.swing.JComboBox<>();
        Ligne5Colonne3 = new javax.swing.JComboBox<>();
        Ligne5Colonne4 = new javax.swing.JComboBox<>();
        Ligne6Colonne1 = new javax.swing.JComboBox<>();
        Ligne6Colonne2 = new javax.swing.JComboBox<>();
        Ligne6Colonne3 = new javax.swing.JComboBox<>();
        Ligne6Colonne4 = new javax.swing.JComboBox<>();
        Ligne7Colonne1 = new javax.swing.JComboBox<>();
        Ligne7Colonne2 = new javax.swing.JComboBox<>();
        Ligne7Colonne3 = new javax.swing.JComboBox<>();
        Ligne7Colonne4 = new javax.swing.JComboBox<>();
        Ligne8Colonne1 = new javax.swing.JComboBox<>();
        Ligne8Colonne2 = new javax.swing.JComboBox<>();
        Ligne8Colonne3 = new javax.swing.JComboBox<>();
        Ligne8Colonne4 = new javax.swing.JComboBox<>();
        Ligne9Colonne1 = new javax.swing.JComboBox<>();
        Ligne9Colonne2 = new javax.swing.JComboBox<>();
        Ligne9Colonne3 = new javax.swing.JComboBox<>();
        Ligne9Colonne4 = new javax.swing.JComboBox<>();
        Ligne10Colonne1 = new javax.swing.JComboBox<>();
        Ligne10Colonne2 = new javax.swing.JComboBox<>();
        Ligne10Colonne3 = new javax.swing.JComboBox<>();
        Ligne10Colonne4 = new javax.swing.JComboBox<>();
        Ligne11Colonne1 = new javax.swing.JComboBox<>();
        Ligne11Colonne2 = new javax.swing.JComboBox<>();
        Ligne11Colonne3 = new javax.swing.JComboBox<>();
        Ligne11Colonne4 = new javax.swing.JComboBox<>();
        Ligne12Colonne1 = new javax.swing.JComboBox<>();
        Ligne12Colonne2 = new javax.swing.JComboBox<>();
        Ligne12Colonne3 = new javax.swing.JComboBox<>();
        Ligne12Colonne4 = new javax.swing.JComboBox<>();
        validerButton = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("<html> <center>Bienvenue dans Mastermind !<br>Devinez la combinaison en un maximum de 12 tours.</center> </html>");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        grillePanel.setBackground(new java.awt.Color(204, 204, 204));
        grillePanel.setLayout(new java.awt.GridLayout(12, 4, 5, 5));

        Ligne1Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        Ligne1Colonne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ligne1Colonne1ActionPerformed(evt);
            }
        });
        grillePanel.add(Ligne1Colonne1);

        Ligne1Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne1Colonne2);

        Ligne1Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne1Colonne3);

        Ligne1Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne1Colonne4);

        Ligne2Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne2Colonne1);

        Ligne2Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        Ligne2Colonne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ligne2Colonne2ActionPerformed(evt);
            }
        });
        grillePanel.add(Ligne2Colonne2);

        Ligne2Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne2Colonne3);

        Ligne2Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne2Colonne4);

        Ligne3Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne3Colonne1);

        Ligne3Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne3Colonne2);

        Ligne3Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne3Colonne3);

        Ligne3Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne3Colonne4);

        Ligne4Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne4Colonne1);

        Ligne4Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne4Colonne2);

        Ligne4Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne4Colonne3);

        Ligne4Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne4Colonne4);

        Ligne5Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne5Colonne1);

        Ligne5Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne5Colonne2);

        Ligne5Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne5Colonne3);

        Ligne5Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne5Colonne4);

        Ligne6Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne6Colonne1);

        Ligne6Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne6Colonne2);

        Ligne6Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne6Colonne3);

        Ligne6Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne6Colonne4);

        Ligne7Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne7Colonne1);

        Ligne7Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne7Colonne2);

        Ligne7Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne7Colonne3);

        Ligne7Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne7Colonne4);

        Ligne8Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne8Colonne1);

        Ligne8Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne8Colonne2);

        Ligne8Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne8Colonne3);

        Ligne8Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne8Colonne4);

        Ligne9Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne9Colonne1);

        Ligne9Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne9Colonne2);

        Ligne9Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne9Colonne3);

        Ligne9Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne9Colonne4);

        Ligne10Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne10Colonne1);

        Ligne10Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne10Colonne2);

        Ligne10Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne10Colonne3);

        Ligne10Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne10Colonne4);

        Ligne11Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne11Colonne1);

        Ligne11Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne11Colonne2);

        Ligne11Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne11Colonne3);

        Ligne11Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne11Colonne4);

        Ligne12Colonne1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne12Colonne1);

        Ligne12Colonne2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne12Colonne2);

        Ligne12Colonne3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne12Colonne3);

        Ligne12Colonne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rouge", "Bleu", "Vert", "Jaune" }));
        grillePanel.add(Ligne12Colonne4);

        getContentPane().add(grillePanel, java.awt.BorderLayout.CENTER);

        validerButton.setText("Valider");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(validerButton, java.awt.BorderLayout.PAGE_END);

        lblMessage.setText("jLabel1");
        getContentPane().add(lblMessage, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        // TODO add your handling code here:

        String[] proposition = new String[4];
        for (int i = 0; i < 4; i++) {
            JComboBox<String> comboBox = (JComboBox<String>) grillePanel.getComponent(ligneVisible * 4 + i);
            proposition[i] = comboBox.getSelectedItem().toString();
        }

        // Comparer la tentative avec la combinaison secrète
        String resultat = comparerCombinaisons(proposition, combinaisonSecrete);

        // Afficher le résultat dans lblMessage
        lblMessage.setText(resultat);

        // Vérifier si le joueur a gagné
        if (resultat.startsWith("Bien placés : 4")) {
            lblMessage.setText("Félicitations, vous avez gagné !");
            validerButton.setEnabled(false); // Désactiver le bouton en cas de victoire
        } else if (ligneVisible == 11) { // Dernière tentative
            lblMessage.setText("Défaite ! La combinaison secrète était : " + String.join(", ", combinaisonSecrete));
            validerButton.setEnabled(false);
        } else {
            afficherProchaineLigne(); // Passer à la ligne suivante
        }
    
   
    

    }//GEN-LAST:event_validerButtonActionPerformed

    private void Ligne2Colonne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ligne2Colonne2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ligne2Colonne2ActionPerformed

    private void Ligne1Colonne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ligne1Colonne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ligne1Colonne1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMindInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMindInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ligne10Colonne1;
    private javax.swing.JComboBox<String> Ligne10Colonne2;
    private javax.swing.JComboBox<String> Ligne10Colonne3;
    private javax.swing.JComboBox<String> Ligne10Colonne4;
    private javax.swing.JComboBox<String> Ligne11Colonne1;
    private javax.swing.JComboBox<String> Ligne11Colonne2;
    private javax.swing.JComboBox<String> Ligne11Colonne3;
    private javax.swing.JComboBox<String> Ligne11Colonne4;
    private javax.swing.JComboBox<String> Ligne12Colonne1;
    private javax.swing.JComboBox<String> Ligne12Colonne2;
    private javax.swing.JComboBox<String> Ligne12Colonne3;
    private javax.swing.JComboBox<String> Ligne12Colonne4;
    private javax.swing.JComboBox<String> Ligne1Colonne1;
    private javax.swing.JComboBox<String> Ligne1Colonne2;
    private javax.swing.JComboBox<String> Ligne1Colonne3;
    private javax.swing.JComboBox<String> Ligne1Colonne4;
    private javax.swing.JComboBox<String> Ligne2Colonne1;
    private javax.swing.JComboBox<String> Ligne2Colonne2;
    private javax.swing.JComboBox<String> Ligne2Colonne3;
    private javax.swing.JComboBox<String> Ligne2Colonne4;
    private javax.swing.JComboBox<String> Ligne3Colonne1;
    private javax.swing.JComboBox<String> Ligne3Colonne2;
    private javax.swing.JComboBox<String> Ligne3Colonne3;
    private javax.swing.JComboBox<String> Ligne3Colonne4;
    private javax.swing.JComboBox<String> Ligne4Colonne1;
    private javax.swing.JComboBox<String> Ligne4Colonne2;
    private javax.swing.JComboBox<String> Ligne4Colonne3;
    private javax.swing.JComboBox<String> Ligne4Colonne4;
    private javax.swing.JComboBox<String> Ligne5Colonne1;
    private javax.swing.JComboBox<String> Ligne5Colonne2;
    private javax.swing.JComboBox<String> Ligne5Colonne3;
    private javax.swing.JComboBox<String> Ligne5Colonne4;
    private javax.swing.JComboBox<String> Ligne6Colonne1;
    private javax.swing.JComboBox<String> Ligne6Colonne2;
    private javax.swing.JComboBox<String> Ligne6Colonne3;
    private javax.swing.JComboBox<String> Ligne6Colonne4;
    private javax.swing.JComboBox<String> Ligne7Colonne1;
    private javax.swing.JComboBox<String> Ligne7Colonne2;
    private javax.swing.JComboBox<String> Ligne7Colonne3;
    private javax.swing.JComboBox<String> Ligne7Colonne4;
    private javax.swing.JComboBox<String> Ligne8Colonne1;
    private javax.swing.JComboBox<String> Ligne8Colonne2;
    private javax.swing.JComboBox<String> Ligne8Colonne3;
    private javax.swing.JComboBox<String> Ligne8Colonne4;
    private javax.swing.JComboBox<String> Ligne9Colonne1;
    private javax.swing.JComboBox<String> Ligne9Colonne2;
    private javax.swing.JComboBox<String> Ligne9Colonne3;
    private javax.swing.JComboBox<String> Ligne9Colonne4;
    private javax.swing.JPanel grillePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
